name: Publish Artifacts

on:
  push:
    branches: [ main ]

jobs:
  createUnityPackage:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Assets/ExtendedUnityEditor.meta" > ExtendedUnityEditor
          find Assets/ExtendedUnityEditor/ -name \*.meta >> ExtendedUnityEditor
      - run: mkdir output

      - uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: 'output/extended-unity-editor.unitypackage'
          include-files: ExtendedUnityEditor
      - uses: actions/upload-artifact@master
        with:
          path: output
          name: extended-unity-editor
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: output/extended-unity-editor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
